development:
  adapter: async

test:
  adapter: async

production: &production
  adapter: redis
  url: redis://redistogo:3b683b0b84196f9f4174be2edf7b2f56@barreleye.redistogo.com:10744/
  host: barreleye.redistogo.com
  port: 10272
  password: 3b683b0b84196f9f4174be2edf7b2f56
  inline: true
  timeout: 1
