# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaf0fe9084e3987bece514fe8a8db5c50dc9bd093305b34a3663c4ae8f2fdc58ed8fd9f5ef578b26c05debf0eab4427c3250505f1b591e8ba41ac5ae41426388

test:
  secret_key_base: 3065618bb1c67fe20ccd06a4b0a553d182ec3bb9dd06cd4dd1dc61fd38ff0a0c1fa117b1bfe28de3067fb6382d4080b5954e260f2b90de5d7e3d23ba84b0c0fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
